import requests
import json
import os
import sys
import pandas as pd
from datetime import datetime
import urllib.parse

def construct_dataset_json(row_data, mapping):
    """
    Constructs the Dataverse JSON for dataset creation based on row data and mapping.
    Handles basic Citation metadata fields.
    """
    fields = []
    
    # Mapping looks like: {"Spreadsheet Column": "dataverse_name"}
    reverse_mapping = {v: k for k, v in mapping.items()}
    
    # 1. Title (Mandatory)
    title = str(row_data.get(reverse_mapping.get('title'), 'Untitled Dataset'))
    fields.append({
        "typeName": "title",
        "typeClass": "primitive",
        "multiple": False,
        "value": title
    })
    
    # 2. Author (Mandatory)
    author_name = str(row_data.get(reverse_mapping.get('authorName'), 'Pale Fire Agent'))
    fields.append({
        "typeName": "author",
        "typeClass": "compound",
        "multiple": True,
        "value": [
            {
                "authorName": {
                    "typeName": "authorName",
                    "typeClass": "primitive",
                    "multiple": False,
                    "value": author_name
                }
            }
        ]
    })
    
    # 3. Contact (Mandatory)
    contact_email = str(row_data.get(reverse_mapping.get('datasetContactEmail'), 'admin@example.org'))
    contact_name = str(row_data.get(reverse_mapping.get('datasetContactName'), 'Admin'))
    fields.append({
        "typeName": "datasetContact",
        "typeClass": "compound",
        "multiple": True,
        "value": [
            {
                "datasetContactEmail": {
                    "typeName": "datasetContactEmail",
                    "typeClass": "primitive",
                    "multiple": False,
                    "value": contact_email
                },
                "datasetContactName": {
                    "typeName": "datasetContactName",
                    "typeClass": "primitive",
                    "multiple": False,
                    "value": contact_name
                }
            }
        ]
    })
    
    # 4. Description (Mandatory)
    desc_val = str(row_data.get(reverse_mapping.get('dsDescriptionValue'), 'Automatically generated by Pale Fire.'))
    fields.append({
        "typeName": "dsDescription",
        "typeClass": "compound",
        "multiple": True,
        "value": [
            {
                "dsDescriptionValue": {
                    "typeName": "dsDescriptionValue",
                    "typeClass": "primitive",
                    "multiple": False,
                    "value": desc_val
                }
            }
        ]
    })
    
    # 5. Subject (Mandatory)
    subject = [str(row_data.get(reverse_mapping.get('subject'), 'Other'))]
    fields.append({
        "typeName": "subject",
        "typeClass": "controlledVocabulary",
        "multiple": True,
        "value": subject
    })

    # 6. Alternative URL (Optional but requested)
    alt_url = row_data.get(reverse_mapping.get('alternativeURL'))
    
    # Fallback to common URL field names if not found via mapping
    url_fallbacks = ['download_url', 'url', 'alternativeURL', 'link', 'source_url', 'uri']
    if not alt_url:
        for fb in url_fallbacks:
            if fb in row_data and pd.notna(row_data[fb]):
                candidate = str(row_data[fb]).strip()
                if candidate.startswith('http'):
                    alt_url = candidate
                    break
    
    if alt_url:
        fields.append({
            "typeName": "alternativeURL",
            "typeClass": "primitive",
            "multiple": False,
            "value": str(alt_url)
        })

    return {
        "datasetVersion": {
            "metadataBlocks": {
                "citation": {
                    "displayName": "Citation Metadata",
                    "fields": fields
                }
            }
        }
    }

def update_dataset_metadata(server_url, api_token, persistent_id, metadata_json):
    # For updating, we target the citation fields
    url = f"{server_url.rstrip('/')}/api/datasets/:persistentId/editMetadata?persistentId={persistent_id}"
    headers = {"X-Dataverse-key": api_token, "Content-Type": "application/json"}
    
    # Extract fields from the construct_dataset_json structure
    fields = metadata_json['datasetVersion']['metadataBlocks']['citation']['fields']
    payload = {"fields": fields}
    
    response = requests.put(url, headers=headers, json=payload)
    if response.status_code in [200, 201]:
        print(f"Successfully updated metadata for {persistent_id}")
        return True
    else:
        print(f"Failed to update metadata: {response.text}")
        return False

def create_dataset(server_url, api_token, parent_alias, metadata_json):
    url = f"{server_url.rstrip('/')}/api/dataverses/{parent_alias}/datasets"
    headers = {"X-Dataverse-key": api_token, "Content-Type": "application/json"}
    
    response = requests.post(url, headers=headers, json=metadata_json)
    if response.status_code in [200, 201]:
        return response.json()['data']['persistentId']
    else:
        print(f"Failed to create dataset: {response.text}")
        return None

def upload_file(server_url, api_token, persistent_id, file_path, target_filename=None):
    url = f"{server_url.rstrip('/')}/api/datasets/:persistentId/add?persistentId={persistent_id}"
    headers = {"X-Dataverse-key": api_token}
    
    filename = target_filename if target_filename else os.path.basename(file_path)
    
    # Dataverse often prefers jsonData even if minimal
    json_data = {
        "description": f"Data file for {filename}",
        "categories": ["Data"],
        "restrict": "false"
    }
    
    try:
        with open(file_path, 'rb') as f:
            files = {
                'file': (filename, f, 'text/csv'),
                'jsonData': (None, json.dumps(json_data))
            }
            response = requests.post(url, headers=headers, files=files)
            
        if response.status_code in [200, 201]:
            print(f"Successfully uploaded {filename} to {persistent_id}")
            return True
        else:
            print(f"Failed to upload {filename} to {persistent_id}")
            print(f"Status: {response.status_code}")
            print(f"Response: {response.text}")
            return False
    except Exception as e:
        print(f"Exception during upload: {str(e)}")
        return False

def main():
    if len(sys.argv) < 5:
        print("Usage:")
        print("  Bulk Upload:   python3 dataverse_uploader.py <server_url> <api_token> <parent_alias> <source_csv> <mapping_json>")
        print("  Single Upload: python3 dataverse_uploader.py <server_url> <api_token> <persistent_id> <file_path> --single")
        print("  Update Meta:   python3 dataverse_uploader.py <server_url> <api_token> <persistent_id> <source_csv_row> <mapping_json> --update")
        sys.exit(1)
        
    server_url = sys.argv[1]
    api_token = sys.argv[2]
    
    if "--single" in sys.argv:
        persistent_id = sys.argv[3]
        file_path = sys.argv[4]
        filename = os.path.basename(file_path)
        upload_file(server_url, api_token, persistent_id, file_path, filename)
        return

    if "--update" in sys.argv:
        persistent_id = sys.argv[3]
        source_csv = sys.argv[4]
        mapping = json.loads(sys.argv[5])
        df = pd.read_csv(source_csv)
        row = df.iloc[0]
        metadata = construct_dataset_json(row, mapping)
        update_dataset_metadata(server_url, api_token, persistent_id, metadata)
        return

    parent_alias = sys.argv[3]
    source_csv = sys.argv[4]
    mapping = json.loads(sys.argv[5])
    
    df = pd.read_csv(source_csv)
    
    for i, row in df.iterrows():
        print(f"\n--- Processing row {i} ---")
        metadata = construct_dataset_json(row, mapping)
        
        # 1. Create Dataset
        pid = create_dataset(server_url, api_token, parent_alias, metadata)
        if not pid:
            continue

        # 2. Extract and Upload Row CSV (URLs are naturally included here)
        os.makedirs("cache", exist_ok=True)
        row_filename = f"row{i}_data.csv"
        temp_csv = f"cache/temp_{row_filename}"
        pd.DataFrame([row]).to_csv(temp_csv, index=False)
        upload_file(server_url, api_token, pid, temp_csv, row_filename)
        os.remove(temp_csv)

if __name__ == "__main__":
    main()
