import requests
import json
import os
import sys
import pandas as pd
from datetime import datetime
import urllib.parse

def is_url(string):
    try:
        result = urllib.parse.urlparse(str(string))
        return all([result.scheme, result.netloc])
    except:
        return False

def construct_dataset_json(row_data, mapping):
    """
    Constructs the Dataverse JSON for dataset creation based on row data and mapping.
    Handles basic Citation metadata fields.
    """
    fields = []
    
    # Mapping looks like: {"Spreadsheet Column": "dataverse_name"}
    reverse_mapping = {v: k for k, v in mapping.items()}
    
    # 1. Title (Mandatory)
    title = str(row_data.get(reverse_mapping.get('title'), 'Untitled Dataset'))
    fields.append({
        "typeName": "title",
        "typeClass": "primitive",
        "multiple": False,
        "value": title
    })
    
    # 2. Author (Mandatory)
    author_name = str(row_data.get(reverse_mapping.get('authorName'), 'Pale Fire Agent'))
    fields.append({
        "typeName": "author",
        "typeClass": "compound",
        "multiple": True,
        "value": [
            {
                "authorName": {
                    "typeName": "authorName",
                    "typeClass": "primitive",
                    "multiple": False,
                    "value": author_name
                }
            }
        ]
    })
    
    # 3. Contact (Mandatory)
    contact_email = str(row_data.get(reverse_mapping.get('datasetContactEmail'), 'admin@example.org'))
    contact_name = str(row_data.get(reverse_mapping.get('datasetContactName'), 'Admin'))
    fields.append({
        "typeName": "datasetContact",
        "typeClass": "compound",
        "multiple": True,
        "value": [
            {
                "datasetContactEmail": {
                    "typeName": "datasetContactEmail",
                    "typeClass": "primitive",
                    "multiple": False,
                    "value": contact_email
                },
                "datasetContactName": {
                    "typeName": "datasetContactName",
                    "typeClass": "primitive",
                    "multiple": False,
                    "value": contact_name
                }
            }
        ]
    })
    
    # 4. Description (Mandatory)
    desc_val = str(row_data.get(reverse_mapping.get('dsDescriptionValue'), 'Automatically generated by Pale Fire.'))
    fields.append({
        "typeName": "dsDescription",
        "typeClass": "compound",
        "multiple": True,
        "value": [
            {
                "dsDescriptionValue": {
                    "typeName": "dsDescriptionValue",
                    "typeClass": "primitive",
                    "multiple": False,
                    "value": desc_val
                }
            }
        ]
    })
    
    # 5. Subject (Mandatory)
    subject = [str(row_data.get(reverse_mapping.get('subject'), 'Other'))]
    fields.append({
        "typeName": "subject",
        "typeClass": "controlledVocabulary",
        "multiple": True,
        "value": subject
    })

    return {
        "datasetVersion": {
            "metadataBlocks": {
                "citation": {
                    "displayName": "Citation Metadata",
                    "fields": fields
                }
            }
        }
    }

def create_dataset(server_url, api_token, parent_alias, metadata_json):
    url = f"{server_url.rstrip('/')}/api/dataverses/{parent_alias}/datasets"
    headers = {"X-Dataverse-key": api_token, "Content-Type": "application/json"}
    
    response = requests.post(url, headers=headers, json=metadata_json)
    if response.status_code in [200, 201]:
        return response.json()['data']['persistentId']
    else:
        print(f"Failed to create dataset: {response.text}")
        return None

def upload_file(server_url, api_token, persistent_id, file_path, target_filename=None):
    url = f"{server_url.rstrip('/')}/api/datasets/:persistentId/add?persistentId={persistent_id}"
    headers = {"X-Dataverse-key": api_token}
    
    filename = target_filename if target_filename else os.path.basename(file_path)
    
    # Dataverse often prefers jsonData even if minimal
    json_data = {
        "description": f"Data file for {filename}",
        "categories": ["Data"],
        "restrict": "false"
    }
    
    try:
        with open(file_path, 'rb') as f:
            # Note: We send the file with the desired filename in the multipart form
            files = {
                'file': (filename, f, 'text/csv'),
                'jsonData': (None, json.dumps(json_data))
            }
            response = requests.post(url, headers=headers, files=files)
            
        if response.status_code in [200, 201]:
            print(f"Successfully uploaded {filename} to {persistent_id}")
            return True
        else:
            print(f"Failed to upload {filename} to {persistent_id}")
            print(f"Status: {response.status_code}")
            print(f"Response: {response.text}")
            return False
    except Exception as e:
        print(f"Exception during upload: {str(e)}")
        return False

def download_remote_file(url, output_dir="cache"):
    try:
        os.makedirs(output_dir, exist_ok=True)
        # Try to get filename from URL
        parsed_url = urllib.parse.urlparse(url)
        filename = os.path.basename(parsed_url.path)
        if not filename or '.' not in filename:
            filename = "data_source_" + datetime.now().strftime("%Y%m%d_%H%M%S")
            # Try to guess extension if missing?
            
        filepath = os.path.join(output_dir, filename)
        
        print(f"Downloading remote data from {url}...")
        response = requests.get(url, stream=True, timeout=30)
        if response.status_code == 200:
            with open(filepath, 'wb') as f:
                for chunk in response.iter_content(chunk_size=8192):
                    f.write(chunk)
            return filepath
        else:
            print(f"Failed to download {url}: Status {response.status_code}")
            return None
    except Exception as e:
        print(f"Error downloading {url}: {str(e)}")
        return None

def main():
    if len(sys.argv) < 5:
        print("Usage:")
        print("  Bulk Upload:   python3 dataverse_uploader.py <server_url> <api_token> <parent_alias> <source_csv> <mapping_json>")
        print("  Single Upload: python3 dataverse_uploader.py <server_url> <api_token> <persistent_id> <file_path> --single")
        sys.exit(1)
        
    server_url = sys.argv[1]
    api_token = sys.argv[2]
    
    if "--single" in sys.argv:
        persistent_id = sys.argv[3]
        file_path = sys.argv[4]
        filename = os.path.basename(file_path)
        upload_file(server_url, api_token, persistent_id, file_path, filename)
        return

    parent_alias = sys.argv[3]
    source_csv = sys.argv[4]
    mapping = json.loads(sys.argv[5])
    
    df = pd.read_csv(source_csv)
    
    for i, row in df.iterrows():
        print(f"\n--- Processing row {i} ---")
        metadata = construct_dataset_json(row, mapping)
        
        # 1. Create Dataset
        pid = create_dataset(server_url, api_token, parent_alias, metadata)
        if not pid:
            continue

        # 2. Extract and Upload Row CSV
        os.makedirs("cache", exist_ok=True)
        row_filename = f"row{i}_data.csv"
        temp_csv = f"cache/temp_{row_filename}"
        pd.DataFrame([row]).to_csv(temp_csv, index=False)
        upload_file(server_url, api_token, pid, temp_csv, row_filename)
        os.remove(temp_csv)

        # 3. Detect and Upload Remote Data Links
        for col_name, value in row.items():
            val_str = str(value)
            if is_url(val_str):
                # Filter out generic or non-data links if needed, 
                # but user says "Never ignore any reference to download"
                remote_file = download_remote_file(val_str)
                if remote_file:
                    upload_file(server_url, api_token, pid, remote_file)
                    # Optional: cleanup remote file?
                    # os.remove(remote_file)

if __name__ == "__main__":
    main()
